### ISSUE TITLE
O(N) algorithm for calculating box-counting dimension

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#117]
In 

> Molteno, T. C. A. (1993). Fast O(N) box-counting algorithm for estimating dimensions. Physical Review E, 48(5), 3263–3266. https://doi.org/10.1103/PhysRevE.48.R3263

The author provides a fast algorithm for calculating the capacity dimension (actually for counting boxes needed to cover a set) which is faster than our generic O(Nlog(N)) version.

The paper is straightforward and easy to implement, taking advantage of binary representation of numbers.

**Comment by apbraun** [comment]
So I would assume since #130 is merged this can now be called closed
