### ISSUE TITLE
Enhanced box and prism assisted algorithms for computing the correlation dimension

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#118]
In this work:

> Bueno-Orovio, A., & Pérez-García, V. M. (2007). Enhanced box and prism assisted algorithms for computing the correlation dimension. Chaos, Solitons and Fractals, 34(2), 509–518. https://doi.org/10.1016/j.chaos.2006.03.043

The authors provide the most optimized (to our knowledge) method for estimating the correlation sum and subsequent dimension.

**Comment by apbraun** [comment]
I would assume this done.
