### ISSUE TITLE
`correlationsum_2` throws `OutOfMemoryError()` when called with multiple radii `ϵs` for a large time series

### ISSUE THREAD

**Issue by apbraun** [JuliaDynamics/ChaosTools.jl#136]
If the correlationsum is calculated in the standard way to calculate the dimension as done in `grassberger`, the `distancematrix` becomes too large and throws an `OutOfMemoryError()`.

Since it takes quite some time to calculate this correlationsum I'm unsure whether this is a problem or if one should just use the version by Theiler that is currently being implemented. The error could however be prevented, if the calculation of the distances is done in incremental order instead of calculating them all in a matrix at once.

This problem is somewhat machine dependent, so if it doesn't occur when trying the given example it should happen when increasing `trajectory_length`:
```julia
using ChaosTools
ds = Systems.henon()
trajectory_length = 200000
ts = trajectory(ds, trajectory_length)
correlationsum(ts, [0.1])
```

**Comment by Datseris** [comment]
?! 

This wasn't happening before, did we alter the original version of the correlation sum? Where it was a double for loop?

**Comment by apbraun** [comment]
No this was on the original version of `correlationsum`, now `correlationsum_2`. I think it should be the call of `d = distancematrix(X, norm)`. This allocates `zeros(eltype(X), N, N)` which becomes quite big for 200000 entries.

**Comment by Datseris** [comment]
Oh damn you are right.

Well, we could change the code so that `count(d[j, i] < ε for j in i+1+w:N)` doesn't use `d` the distance matrix but instead computes the distances on the spot, that is true.

**Comment by Datseris** [comment]
Ah no wait. I think the best way to solve this is to simply alter the doucmentation string. The optimized version where `ε` is a vector needs the distance matrix otherwise you recompute all distances. We can simply state this in teh docstring, that if you have too large of a dataset you'll run out of memory and thus do the calculations individually, since they never allocate a matrix: `[correlationsum(..., ε) for ε in εs]`.

**Comment by apbraun** [comment]
Seems reasonable. I'll include it inside of #134.
