### ISSUE TITLE
`boxed_correlationsum` is lacking a Theiler window

### ISSUE THREAD

**Issue by apbraun** [JuliaDynamics/ChaosTools.jl#146]
The `boxed_correlationsum` could possibly also feature a Theiler window as in the "classic" `correlationsum`. I'm unsure whether this is computationally viable.

**Comment by Datseris** [comment]
Is it discussed in the paper?

**Comment by apbraun** [comment]
In the original by Theiler that introduced the `boxed_correlationsum`? No.

**Comment by Datseris** [comment]
Let's consider this after I see your comparison plots

**Comment by apbraun** [comment]
ok
