### ISSUE TITLE
Correlation sum q <= 1 warnings

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#153]
@apbraun  both methods provide warnings when used for `q <= 1`. The vector "optimized" one, but also the straightforaward single-ε one.

Why do we have warnings like
```julia
    q <= 1 && @warn "This function is currently not specialized for q <= 1" *
    " and may show unexpected behaviour for these values."
```
What's the problem? What "specialization" is missing?

**Comment by apbraun** [comment]
The approach in these functions is to use the approach where the radius is fixed and the number of points inside the sphere are computed. If a point has no neighbour with radius `ε`, the inner sum is zero. This sum is taken to the power of `q - 1`. If `q` is smaller or equal to 1, this becomes infinite and the correlation sum is useless for this value of `ε`. Should I write the warning more explicit?

**Comment by Datseris** [comment]
Aaaaaaah. I don't think we should have a warning at all. The message is missleading... There isn't any specialization you could be doing, this is simply because of the definition of the correlation sum. We have to remove it.

An _alternative_ definition of the correlation sum, that instead gets a fixed amount of nearest neighbors and calculates their average distance, is something we can consider, but for now I don't think this is a priority.

**Comment by apbraun** [comment]
Ok. Another question: Is it possible to access version 1.21 using the julia package manager?

**Comment by apbraun** [comment]
Should I remove it or do you do it. If I should do it I'm unsure which number to write into the `Project.toml` since the file says 1.21.1 and the changelog says version 1.22.

**Comment by Datseris** [comment]
I'll do it!
