### ISSUE TITLE
q-order correlationsum is unintuitive

### ISSUE THREAD

**Issue by apbraun** [JuliaDynamics/ChaosTools.jl#159]
The q-order correlationsum currently follows the definition given by [Kantz and Schreiber](https://doi.org/10.1017/CBO9780511755798):
![Screenshot from 2021-02-02 11-53-05](https://user-images.githubusercontent.com/11183188/106590357-489bf680-654d-11eb-834e-72e4ce6e2071.png)
with
![Screenshot from 2021-02-02 11-53-24](https://user-images.githubusercontent.com/11183188/106590368-4cc81400-654d-11eb-963a-44cf9e0a51fb.png)
or in the  case of the boxed correlationsum:
![Screenshot from 2021-02-02 11-52-45](https://user-images.githubusercontent.com/11183188/106590399-55204f00-654d-11eb-9224-aeb183caf0de.png)

 This leads to the requirement of multiplication by a factor of `1/(q-1)` after the linear regression has been made. Taking the definition given by [Grassberger on scholarpedia](http://www.scholarpedia.org/w/index.php?title=Grassberger-Procaccia_algorithm&action=cite&rev=91330):
![Screenshot from 2021-02-02 11-56-30](https://user-images.githubusercontent.com/11183188/106590771-bf38f400-654d-11eb-9a05-dff0c5fdfc0d.png)

and applying all other corrections, would solve this issue and make the q-order correlationsum more accessible.

**Comment by apbraun** [comment]
`n_i` equals the inner sum in the former sums. It is the number of points within radius `ε` of the point `x_i`.

 The whole sum defined by Grassberger is equal to the lower version with the exception of taking it to the power of `1/(q-1)`, which is the same as the multiplication of that same factor to the logarithm afterwards but a user needs no knowledge about this, when using the function.

**Comment by Datseris** [comment]
yES, I agree with this suggestion, and also adding the formula to the docstrings (but also writing the simple q=2 version that is really easy to read)
