### ISSUE TITLE
Problem with default SimpleATsit5 solver

### ISSUE THREAD

**Issue by awage** [JuliaDynamics/ChaosTools.jl#171]
The default solver SimpleATsit5 does not integrate correctly the duffing oscillator for a fixed period step 2pi/omega

The integrator Tsit5 from DifferentialEquations seems to give the correct solution. I suppose there is some kind of adaptative step problem in the solver. The solution is the same with higher order solvers (Vern7, etc) 

```jl
using DifferentialEquations
using DynamicalSystems

ds = Systems.duffing(β = -1, ω = 0.3, f = 0.1, [0.1, 0.2])
integ  = integrator(ds; alg=Tsit5(),  reltol=1e-8)
step!(integ,2π/0.3*20,true)
u=zeros(200,2)
for k in 1:200
   step!(integ,2π/0.3,true)
   u[k,:] = integ.u
end


ds = Systems.duffing(β = -1, ω = 0.3, f = 0.1, [0.1, 0.2])
integ  = integrator(ds; reltol=1e-8)
step!(integ,2π/0.3*20,true)
v=zeros(200,2)
for k in 1:200
   step!(integ,2π/0.3,true)
   v[k,:] = integ.u
end

# v is the "wrong" solution, "u" is just a fixed point. 
plot(v[:,1],v[:,2],seriestype=:scatter)
plot!(u[:,1],u[:,2],seriestype=:scatter)
```

ChaosTools v1.27.0

**Comment by Datseris** [comment]
Hmm, yeah I can confirm :( Unfortunately this seems unrelated with DynamicalSystems.jl. Doing `@edit step!(integ,2π/0.3*20,true)` in the second case brings you immediatelly to the source of SimpleDiffEq.jl. I will open an issue there.

**Comment by Datseris** [comment]
Closing in favor of https://github.com/SciML/SimpleDiffEq.jl/issues/46

**Comment by Datseris** [comment]
@awage it was a simple fix after all : https://github.com/SciML/SimpleDiffEq.jl/pulls/47 ,  soon we will have it released

**Comment by awage** [comment]
Great! How can I submit the correct figure for the stroboscopic map in the docs? I send you the picture?

**Comment by Datseris** [comment]
I've simply re-run documentation product. It should use the latest package versions and thus compute correct figure when it's done. https://github.com/JuliaDynamics/DynamicalSystems.jl/runs/2574286022?check_suite_focus=true
