### ISSUE TITLE
Attractor "matching"

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#176]
Recent PRs introduced some really great functionality regarding estimating basins of attraction: `basins_general`.

I've started applying these methods, but I quickly encountered something I feared: the attractor IDs are not "matched" when computing basins for different parameters. For example, I am interested in the basins of the magnetic pendulum when changing one of the magnet's strength. I get:

![image](https://user-images.githubusercontent.com/19669089/119643282-da40b400-be1b-11eb-90d2-ccb804c12d11.png)

Exactly because the enumeration of the attractors is somewhat "random", I get different numbers for the "same" attractors. Now, I know that "same" isn't really valid here, as different attractors exist at different parameters, but you get my point.

Here is one proposal I have: create a function `match_attractors!(b1, a1, b2, a2)` that tries to match the basin and attractors at parameter "1" with those at "2". We could have different ways of how to do it. Ideas:

1. maximum overlap of basins = same attractors
2. State space distance between attractors `a1` and `a2`

I'll start a PR on this soon. @awage any other ideas?

**Comment by awage** [comment]
Hopefully there is no bifurcations involved and you can track quite safely the attractors with some metric. 

Another possibility is to give to `basin_general` a initial guess on where the attractors are. The algorithm start looking at these point first and label the attractors in the same order. If the basins hasn't changed too much it should give the same labelling. 

This is not difficult to do. It is at the cost of an additional keyword. Tell me if you need help on this one.
