### ISSUE TITLE
Basins for 2D Poincare map finds incorrect attractors

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#182]
MWE:
```julia
using DynamicalSystems
ds = Systems.rikitake(μ = 0.47, α = 1.0)
plane = (3, 0.0)
pmap = poincaremap(ds, (3, 0.), Tmax=1e6;
    idxs = 1:2, rootkw = (xrtol = 1e-12, atol = 1e-12), reltol=1e-9
)
xg = yg = range(-6.,6.,length=200)
basin, attractors = basins_2D(xg, yg, pmap)

attractors[1]
```
```
julia> attractors[1]
3-dimensional Dataset{Float64} with 9 points
 -2.13894   1.1333   0.190275
  2.30516  -1.41217  0.214518
  2.33192  -1.38681  0.129178
 -2.19281   1.06658  0.0302465
  2.35349  -1.36082  0.0550896
 -2.12238   1.14843  0.235889
  2.28525  -1.42716  0.274113
 -2.17312   1.09433  0.0907607
 -2.17888   1.08661  0.0732694
```

As you can see, the z-coordinate is way off. It should instead be exactly 0.

I think this happens because of the modification we did for `basins_general` where we record the full state. Howver in the poincare map we have to be a bit careful. Stepping the integrator and then getting `integ.u` is **incorrect**. The poincare map logic does an interpolation and then returns the interpolated state, but here we are missing this interpolation. We need to get the state the integrator returns upon calling `u = step!(pmap)`.

cc @awage as well.

**Comment by awage** [comment]
I think I understand. This is why I had some weird results with `rikitake`. Maybe it is possible to modify `get_state` to return the interpolated state instead of the integrator state.

**Comment by awage** [comment]
There is a possible fix: you can add the interpolated state to the struct `PoincareMap` and have it returned with `get_state`

This is not consistent with the definition of `get_state` that return the state of the integrator but it is a minimal change to have a correct projected state on the map for basins.

**Comment by Datseris** [comment]
We can agree that at the moment PoincareMap shouldn't be supported. Will remove it from the documentation until we fix these issues.

**Comment by awage** [comment]
I leave a possible solution in PR #190.
