### ISSUE TITLE
Orbit Diagram calculation returns rootfinding error

### ISSUE THREAD

**Issue by rusandris** [JuliaDynamics/ChaosTools.jl#185]
**Issue description**
 I'm trying to make an orbitdiagram for a continuous system using `produce_orbitdiagram()` but I keep getting an error from Roots.jl's `find_zero()`.
`ArgumentError: The interval [a,b] is not a bracketing interval.
You need f(a) and f(b) to have different signs (f(a) * f(b) < 0).
Consider a different bracket or try fzero(f, c) with an initial guess c.` 
More precisely, this is from bracketing.jl, `init_state()`.
I understand this means that both points of the integrator ended up on one side of the plane. Which is weird, because `poincaresos()` guarantees that this won't happen. I've looked into it a little and `plane_distance` is the function that gets propagated as `f` into Roots.jl `find_zero()`. `planecrossing(integ.u)*planecrossing(integ.uprev)` is always negative (as it should be), but somehow `plane_distance` sometimes gives two positive values  to bracketing's `init_state()`. Is this just a tolerance issue? Do you guys have any thoughts on this? What am I missing?

**Minimal Working Example**
```
function skipsum(a,i)
    x = a[1:2:end]
    return sum(x) - a[i]
end

function att_din!(du,u,p,t)
    n = convert(Int32,p[3])
    for i in 1:2:(2*n)
        du[i] = p[1]*u[i]*(1 - (1 - p[2])*u[i+1] - p[2]/(n-1)*skipsum(u,i))
        du[i+1] = u[i] - u[i+1]
    end
end

n = 5
g = 30
w = 0.14 
p = [g,w,n]
state = rand(2*n) 
ds = ContinuousDynamicalSystem(att_din!,state,p)
plane = (1,1)
i = 2
p_index = 2
pvalues = [0.14:0.01:0.2;]
tfinal = 30
Ttr = 30
orbit_diagram = produce_orbitdiagram(ds,plane,i,p_index,pvalues;direction = -1,tfinal = tfinal,
                                    Ttr = Ttr,printparams=true,alg = DP5(),
                                    rootkw = (xrtol = 1e-6, atol = 1e-6),reuse=false)
```

**Comment by Datseris** [comment]
Hi, thanks for opening the issue.

1. Can you please paste the error stacktrace as well?
2. Can you please post a picture of a trajectory of your dynamical system , projected in 3D space, and also a picture of the hyperplane? Or in general some clues, visual or not, whether the hyperplane is well defined, or if it is ill defined. An ill defined hyperplane would be e.g. something the trajectory only crosses tangentially
