### ISSUE TITLE
A test for fractal boundaries based on the basin entropy

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#191]
Paper: https://www-sciencedirect-com.e-bis.mpimet.mpg.de/science/article/abs/pii/S1007570420304184

![image](https://user-images.githubusercontent.com/19669089/124356859-b04b9000-dc18-11eb-8307-6db298c2da25.png)

Would be a nice addition to our basins of attraction functionality!

@awage I do not have access to the paper, unfortunately, do you have a pre-print somewhere?

**Comment by awage** [comment]
I put it on my list of PR to submit. But first I want to fix the uncertainty dimension for basins of any dimension.

[1-s2.0-S1007570420304184-main.pdf](https://github.com/JuliaDynamics/ChaosTools.jl/files/6760600/1-s2.0-S1007570420304184-main.pdf)

**Comment by awage** [comment]
closed with #196
