### ISSUE TITLE
basin stability of multi-stable dynamical systems using clustering

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#211]
https://link.springer.com/article/10.1007%2Fs11071-021-06786-5

Method from Stender & Hoffman

This paper implements a method to calculate basin stability that works for high dimensional systems efficiently, by combining Monte Carlo sampling and a clustering algorithm. Perhaps it can interplay well with our existing `basins_of_attraction` and tipping points related stuff.

The method is implemented open source in matlab so it should be an easy port.

**Comment by KalelR** [comment]
Hi, I'm interested in doing this! I can work on it and open a PR once I have a first version ready. Would that be ok?

**Comment by Datseris** [comment]
hI @KalelR , great that you say this. I'm also interested in working on this and I have already sketched out the documentation string of the function. Tell you what: I first open a pull request sketching out the function input and output, and then you can take it from there?

**Comment by KalelR** [comment]
Sure, that'd be great!

**Comment by awage** [comment]
If you don't mind I would like to participate. I am very interested in the sampling aspect of the basin. It will be very interesting for systems with high dimension (for example a network of coupled oscillators).

**Comment by KalelR** [comment]
Oh, that's amazing, I'd be interested in networks also. I have implemented a decent part of the code already (I had started a bit before commenting here). Once @Datseris opens the pull request, I can commit what I have so far.

**Comment by Datseris** [comment]
Implemented in https://github.com/JuliaDynamics/ChaosTools.jl/pull/219
