### ISSUE TITLE
improve speed/accuracy: lyapunov(..): integrate perturbed and unperturbed trajectory simultaneously

### ISSUE THREAD

**Issue by RainerEngelken** [JuliaDynamics/ChaosTools.jl#31]
Instead of separately iterating integ1 and integ2, they should be iterated together. Otherwise, the accumulate different noise along with their trajectories in every single step during the integration of the ODE. If they are iterated together (which means each time point is exactly the same), they would accumulate much less noise, therefore a larger reltol and abstol can be used. I have not tested this in ChaosTools.jl but I have seen a large difference in my own code (implemented unfortunately before ChaosTools came into existence).

**Comment by Datseris** [comment]
Yeap this one of the plans.

We are overhauling how systems are defined. A part of the overhaul is to define a `ParallelIntegrator` that integrates many initial states in parallel!

**Comment by RainerEngelken** [comment]
Nice!
