### ISSUE TITLE
'DeterministicIteratedMap' not defined

### ISSUE THREAD

**Issue by jty-computation** [JuliaDynamics/ChaosTools.jl#331]
**Describe the bug**
Attempting run example given in docs: https://juliadynamics.github.io/ChaosTools.jl/stable/orbitdiagram/#ChaosTools.orbitdiagram
Running example as given returns "ERROR: LoadError: UndefVarError: `DeterministicIteratedMap` not defined"

**Minimal Working Example**

using ChaosTools, CairoMakie

logistic_rule(x, p, n) = @inbounds SVector(p[1]*x[1]*(1-x[1]))
logistic = DeterministicIteratedMap(logistic_rule, [0.4], [4.0])

i = 1
parameter = 1
pvalues = 2.5:0.004:4
n = 2000
Ttr = 2000
output = orbitdiagram(logistic, i, parameter, pvalues; n, Ttr)

L = length(pvalues)
x = Vector{Float64}(undef, n*L)
y = copy(x)
for j in 1:L
    x[(1 + (j-1)*n):j*n] .= pvalues[j]
    y[(1 + (j-1)*n):j*n] .= output[j]
end

fig, ax = scatter(x, y; axis = (xlabel = L"r", ylabel = L"x"),
    markersize = 0.8, color = ("black", 0.05),
)
ax.title = "Logistic map orbit diagram"
xlims!(ax, pvalues[1], pvalues[end]); ylims!(ax,0,1)
fig

**Package versions**
DynamicalSystems v2.1.3
DynamicalSystemsBase v2.3.2
Julia Version 1.10.2

**Comment by Datseris** [comment]
DynamicalSystems v2.1.3 is too old. We are in v3 land.
