### ISSUE TITLE
Test `lyapunov` for negative exponents.

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#34]
# Issue Description
The latest PR #33 made it possible for `lyapunov` to find negative exponents for stable systems.

I don't have any systems to test it with though! Maybe  @RainerEngelken can be kind to give us an example?

**Comment by RainerEngelken** [comment]
Mmh, what about ```du = 0.9u``` ;-)
For a less trivial example, you could just go in the Lorenz system outside the chaotic regime.

**Comment by Datseris** [comment]
Rainer you ruined me! I was trying to test `du = 0.9u` and it wasn't working. Took me a good 10 minutes to realise that for continuous systems you need `-0.9`...

**Comment by RainerEngelken** [comment]
Glad you figured it out :))
