### ISSUE TITLE
New method: definition of chaos by Ott [$100]

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#4]
_From @Datseris on October 20, 2017 15:22_

Ott (et al) came up with a definitive way to claim whether or not a system is chaotic. This was done for the 25th anniversary of the journal Chaos.

In the article [Defining Chaos](http://aip.scitation.org/doi/10.1063/1.4922973) he and Brian R. Hunt define a quantity called "expansion entropy" which can characterize chaoticity.

It would be cool to have a function that computes that! The paper also includes a numerical algorithm to compute the quantity.

_Copied from original issue: JuliaDynamics/DynamicalSystems.jl#39_

**Comment by yuxiliu1995** [comment]
I've understood the paper and is now learning the codebase. Should start coding soon.

**Comment by Datseris** [comment]
Cool+awesome! My recommendation in these scenarios is to always open a WIP PR so that we can comment directly on code.

**Comment by yuxiliu1995** [comment]
Now it's closed.

**Comment by yuxiliu1995** [comment]
I got the bounty.
(Bountysource took 10% off, though. Consider not using that as a middleman?)

**Comment by Datseris** [comment]
Sure, if you know alternatives that both take care of the legal side from my end, as well as ensure that the developer is guaranteed to get their money, let me know.

@yuxiliu1995 I am really conflicted on where I should put this in the docs. There are two places:

1. [Chaos Detection](https://juliadynamics.github.io/DynamicalSystems.jl/dev/chaos/chaos_detection/)
2. [Entropies and dimensions](https://juliadynamics.github.io/DynamicalSystems.jl/dev/chaos/entropies/).

By "name", it feels like it fits more in 2. But even though the method computes some kind of entropy, this quantity is mostly used for detecting chaos... What do you think?

**Comment by yuxiliu1995** [comment]
It can go both places, but since it sounds like it's an entropy, so it probably goes to "Entropies and dimensions", since people would look up something about entropy at a place where entropies are listed.

**Comment by asinghvi17** [comment]
Maybe put a reference to it in Chaos Detection as well?

**Comment by Datseris** [comment]
Good ideas thanks. Once we have https://github.com/JuliaDynamics/DrWatson.jl/pull/127/ done I'll do this (at the moment it is not possible to build the docs of DynamicalSystems.jl because of a python incompatibility. really looking forward to dropping python all together, and once Makie is matured, also drop PyPlot).
