### ISSUE TITLE
Increase performance of `non0hist` [$100]

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#58]
# The goal

Maybe we can make `non0hist` function faster, by using a specialized datastructure instead of the standard Julia dictionary. Or maybe there is an even better approach that doesn't use dictionaries at all (see below for the algorithm). I am really bad at performance optimization so when I wrote the function I did not really know whether there is a better plan. I think it is best to ask on Discourse.

# The current approach
`non0hist` produces a histogram in multidimensional space. However, it does it in a special, very cheap way. From the docstring:

> This method is effecient in both memory
> and speed, because it uses a dictionary to collect the information of bins with
> elements, while it completely disregards empty bins. This allows
> computation of entropies of high-dimensional datasets and
> with small box sizes `ε` without memory overflow.
> 

For reference, here is the current implementation:

(please recall: `Dataset` is nothing more than a wrapper of `Vector{SVector}`!)
```julia
function non0hist(ε::Real, data::AbstractDataset{D, T}) where {D, T<:Real}
    # Initialize:
    mini = minima(data)
    L = length(data)
    # Perform "Histogram":
    # `d` is a dictionary that contains all the histogram information
    # the keys are the bin edges indices and the values are the amount of
    # datapoints in each bin
    d = Dict{SVector{D, Int}, Int}()
    for point in data
        # index of datapoint in the ranges space:
        # It is necessary to convert floor to Int (representation issues)
        ind::SVector{D, Int} = floor.(Int, (point - mini)/ε)

        # Add 1 to the bin that contains the datapoint:
        d[ind] = get(d, ind, 0) + 1
    end
    return collect(values(d))/L
end
```

---

# The bounty

Any PR that _generally_ increases the performance of `non0hist` will be accepted as winning the bounty. You don't have to come up with orders of magnitude gain: something x2 gain is already massive, since the function is on the order of several `ms`.

EDIT: ALSO SEE THE CODE HERE: https://github.com/heliosdrm/RecurrenceAnalysis.jl/blob/master/src/delay.jl

**Comment by Datseris** [comment]
reminder: `Dataset` is nothing more than vector of `SVector`

**Comment by Datseris** [comment]
MAgic line from user `@gsoleilhac `:

```
        d[ind] = get(d, ind, 0) + 1
```

**Comment by KristofferC** [comment]
Would be useful with input data, expected output and benchmarks.

**Comment by Datseris** [comment]
here you go sir:

```
using ChaosTools, BenchmarkTools

ds = Systems.towel() # 3D chaotic system

data = trajectory(ds, 100000) # I know this dataset is around 2-dimensional
# but of course `data` is stored as Vector{SVector{3}}
# so topological dimension is 3 but hausdorf dimension is 2

for ε in [0.1, 0.01, 0.001]
    println("ε = $ε")
    @btime non0hist($ε, $data)
    g = genentropy(1.0, ε, data)
    println("with entropy = $g")
end
```

```
ε = 0.1
  42.921 ms (14 allocations: 14.95 KiB)
with entropy = 4.762599382598514
ε = 0.01
  53.339 ms (37 allocations: 3.05 MiB)
with entropy = 9.471958080074165
ε = 0.001
  72.199 ms (43 allocations: 12.48 MiB)
with entropy = 11.463669293018897
```

(notice that `genentropy` calls `non0hist` and then does some veeery simply computations in comparison to what `non0hist` does. So pretty much all performace comes from `non0hist`.)
