### ISSUE TITLE
HAVOK: Chaos as an intermittently forced linear system

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#61]
HAVOK is a new method published recently in nature communications: https://www.nature.com/articles/s41467-017-00030-8

It describes a way where any chaotic system can be turned into a (higher-dimensional) linear system with a single (nonlinear) forcing term. 

- The process is data-driven
- Universal method; it is the same for any system (irrespectively of how good the results are of course)
- Relies on delay embeddings, which we have great support for
- Seems to be a great tool for predicting reversal events, something that (to the best of my knowledge) other prediction methods are not very good at.

This is significantly large project and can also become a very big portion of a Bachelor thesis, and we already have ideas how to make a full thesis out of it. 

Contact me if you are interested!

**Comment by pfcrowe** [comment]
Hi George, I wondered if this would be appropriate for GSoC and what is the best way to communicate?
Cheers, Peter

**Comment by Datseris** [comment]
I am closing this. Some bachelor project implemented this and in the end we decided its not worth implementing.
