### ISSUE TITLE
Feature request: period estimation

### ISSUE THREAD

**Issue by asinghvi17** [JuliaDynamics/ChaosTools.jl#88]
# Issue Description

Feature request for periodicity estimation

# Expected Behavior

An interface which can take in a `DynamicalSystem`, timeseries or `Dataset` and return its frequency (or period)

# MWE

```julia
# setup
using Pkg; pkg"add Hilbert"
using Hilbert


data = sin.(0:π/10:3π)

H = Hilbert.hilbert(data[:, :]) # the function expects a 2d array but we're giving it a 1d timeseries

ϕ₀ = arg(H[1]) # the initial angle

for i in eachindex(H)[2:end]
    # if the tangent vector has completed a full rotation
    arg(H[i]) ≈ ϕ₀ && println(i);
end
```

# Implementation

As discussed on Slack, credit to @Datseris:

>Okay, I think this is interesting to have, and you should open a feature request issue in ChaosTools about it. But I need to tell you that what you want has a clear definition in exactly periodic systems. When one considers quasi-periodicity the situation is not so clear anymore with respect to what you would call a "period time".
A valid approach is the Hilbert transform, and specifically the tangential vector to the vector of the Hilbert transform.
When the tangential vector has performed one rotation, then this is a good approximation for "one period"

There are two questions that one asks when dealing with suspected periodicity: 

1. What is the _period_ of my system? I.e. what is the temporal span that the system needs to return to the state it started at?
2. Is my system _periodic_ for the given parameters (and initial condition)?

These are two different questions. We have full support for question number 2.  This feature request is for question number 1.

**Comment by asinghvi17** [comment]
I should mention that the `Hilbert.jl` package is pretty small - it may make sense to replicate an optimized version of its functionality here.

**Comment by Datseris** [comment]
That is a great idea. And yes I fully concur to have an Hilbert implementation here. If the original package is MIT licensed we can even get parts of the code for free. In general it is not worth it (in my personal view) to depend on a small package for small functionality.

**Comment by Datseris** [comment]
A comment on the API: 
> An interace which can take in a DynamicalSystem and return its frequency (or period)

I think it is advantageous to take the input be a regular timeseries or a `Dataset` instead of a `DynamicalSystem`.

**Comment by Datseris** [comment]
Whatever implementation we add here, we should test it also versus chaotic oscillatory systems like e.g. the Roessler attractor. Notice that the Hilbert proposed method will estimate quite accurately a period for these systems, and this will be a valid number for the period. We should only make sure that we properly document what this estimation is, and why it works even in systems that are not "truly periodic".

**Comment by asinghvi17** [comment]
>  If the original package is MIT licensed we can even get parts of the code for free.

It is!  https://github.com/fpreiswerk/Hilbert.jl

**Comment by asinghvi17** [comment]
An example for the simple sine wave:

```julia
using Hilbert

"""
    arg(z::Complex)

Computes the "angle" of the given complex number
as a vector away from the real axis, counterclockwise.
"""
arg(z::Complex) = atan(z.im, z.re)

"""
    find_period(data)

Uses the Hilbert transform to determine
the periodicity of the dataset.
This function assumes that the data is known to be
periodic.

Returns the index of the first entry that is 2π away from the initial entry.

!!!note
Currently implemented only for one dimension.
"""
function find_period(data; atol = 0.005) # TODO find a nice atol, this is okay for now

    # the function expects a 2d array but we're giving it a 1d timeseries
    H = Hilbert.hilbert(data[:, :])

    ϕ = arg.(H)

    ϕ₀ = ϕ[1]

    Δϕ = 0

    for i in eachindex(ϕ)[2:end]

        Δϕ += ϕ[i] - ϕ[i-1]

        # if the tangent vector has completed a full rotation
        if isapprox(ϕ[i], ϕ₀; atol = atol)

            # println(i)
            # 
            # println(Δϕ)

            isapprox(Δϕ, 0; atol = atol) && return i
            
        end

    end

    return -1

end

find_period(sin.(0:0.01:8π)) # returns 629
(0:0.01:8π)[1886]./π # 2.000...
```

**Comment by asinghvi17** [comment]
The Δϕ part is still a bit weird.  The problem, as always, remains that the error tolerance is very hard to establish - maybe this as a sanity check could be 3x the normal atol or something...

**Comment by asinghvi17** [comment]
Reworked for efficiency:
```julia
"""
    find_period(data; atol = 0.005, ptol = 5*atol)

Uses the Hilbert transform to determine
the periodicity of the dataset.
This function assumes that the data is known to be
periodic.

Returns the index of the first entry that is 2π away from the initial entry.

Arguments
***

- atol - The error tolerance for the phase difference between indices.
- ptol - The error tolerance for what constitutes "one rotation" of the tangent vector.

!!!note
Currently implemented only for one dimension.
"""
function find_period(data; atol = 0.005, ptol = 5*atol)

    # the function expects a 2d array but we're giving it a 1d timeseries
    H = Hilbert.hilbert(data[:, :])

    ϕ = arg.(H)

    ϕ₀ = ϕ[1]

    Δϕ = 0

    for i in eachindex(ϕ)[2:end]

        Δϕ += abs(ϕ[i] - ϕ[i-1])

        # if the tangent vector has completed a full rotation
        if isapprox(Δϕ, 4π; atol = ptol) # why 4π?

            println(i) # debuggingg info

            println(Δϕ) # debugging info

            isapprox(ϕ[i], ϕ₀; atol = atol) && return i # second check - phase angle should be accurate...

        end

    end

    return -1

end
```

and tests:

```
using Test

@testset "period estimation" begin

        @test find_period(sin.(0:0.01:8π)) == 629

        @test find_period((x -> sin(x) + cos(2x)).(0:0.01:8π)) == 629

end
```

Currently, the first test passes, but the second doesn't.  I'll keep working on it in my spare time, but that's kind of limited at the moment.

**Comment by Datseris** [comment]
Hi @asinghvi17  this is really nice progress indeed. In fact this is something so tangible that I would highly recommend starting a pull request instead of continuing the discussion here. This would allow me to:

* Give advice on specific code lines
* Directly contribute as well!

You can put your function in the file `periodic.jl`. Also, is your implementation completely your own, or have you also gotten inspiration from somewhere?
