### ISSUE TITLE
YIN, a fundamental frequency estimator for speech and music

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/ChaosTools.jl#92]
In #91 and #89 we implemented some methods to estimate the dominant period (or conversely dominant frequency) from a timeseries. @asinghvi17  suggested Yin as yet another method to do it, as it is described here:

http://audition.ens.fr/adc/pdf/2002_JASA_YIN.pdf
(implemented in Python at https://github.com/patriceguyot/Yin)

(for now I structure this as "low priority" only because we have already quite a bit of methods to find dominant period)

**Comment by Datseris** [comment]
Oh wow, the python implementation is only 250 lines of code (which would translate to 100 lines of Julia code :) ) so I'll put the labels good first issue and easy here!

**Comment by asinghvi17** [comment]
Just tackling some small fry for the Julia port since I have time:

```julia
function differenceFunction_original(x, N, tau_max)
    """
    Compute difference function of data x. This corresponds to equation (6) in [1]
    Original algorithm.
    :param x: audio data
    :param N: length of data
    :param tau_max: integration window size
    :return: difference function
    :rtype: list
    """
    df = zeros(eltype(x), tau_max)
    for tau in 2:tau_max:
         for j in 1:(N-tau_max):
             df[tau] += (x[j] - x[j + tau]) ^ 2
    return df
```

**Comment by FuturizeHandgun** [comment]
I'm interested in implementing this in Julia!

**Comment by Datseris** [comment]
@FuturizeHandgun again, this is awesome that you'd wanna do that. Again, in my eyes, the best way is to start a WIP PR and ask questions if you have anY!

**Comment by Datseris** [comment]
PR https://github.com/JuliaDynamics/ChaosTools.jl/pull/93  had some initial code. Should be a matter of minutes for someone to take over the PR and finish this.

**Comment by KalelR** [comment]
Hey, I can do this. Can I reopen the PR, or should I create a new one?

**Comment by Datseris** [comment]
New one for sure. You can start a branch directly from ChaosTools.jl this time (I've invited you to the org)

**Comment by KalelR** [comment]
Oh, that's amazing, thanks! :) I've pushed the ap/yin branch, and opened the PR to main.
